import * as React from 'react'
import Head from 'next/head'
import { Button } from '@interads/ui'

export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Demo</h1>
        <Button />
      </main>
    </React.Fragment>
  )
}
